### ISSUE TITLE
About - DevBlog

### ISSUE THREAD

**Issue by Heebe** [torch2424/Fight#95]
I think it would be a good addition to the DevBlog if there was post under the Category "About the Team" or a part of the site that is an actual "About Us". The format could be like it is in this image, were we all each have a photo of us, write little bio on why you're happy to work as a developer for games or why you do what you're doing, and a small list on games you have worked on. That little list will grow throughout the years and it will make for an amazing reference page for all of us. I just need to know if this is a cool and interesting idea, and if so, @torch2424 build it into the site? Cause he's the one who programmed the site.
![about](https://cloud.githubusercontent.com/assets/7026914/8561030/a9d2881c-24d3-11e5-95fa-4bf6d1ff663f.png)

**Comment by torch2424** [comment]
@Heebe Yeah I can get on that. And I saw your texts and stuff by the way. Please keep in mind I have alot of stuff to do. I work 9 hours a day Monday-Wednesday, and I still have some freelance contracts to finish up before summer ends. So I've been quite busy. I try to dedicate about 20 hours a week to the game though. So I know you weren't rushing me to do anything, but yeah just give me a to-do list I can do when I have time. That's why I like the github issue system :)

**Comment by torch2424** [comment]
@Heebe I need profile pictures from everyone to do this!

**Comment by torch2424** [comment]
Finished and looks SUPPPEERRR good due to the power of basic html and inline css in wordpress.

http://www.nocomplygames.com/about/
